<?php



/**
 * This class defines the structure of the 'archive_jid_prefs' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Tue Sep 30 17:21:54 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class ArchiveJidPrefsTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.ArchiveJidPrefsTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('archive_jid_prefs');
        $this->setPhpName('ArchiveJidPrefs');
        $this->setClassname('ArchiveJidPrefs');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(false);
        // columns
        $this->addPrimaryKey('US', 'Us', 'VARCHAR', true, 2047, null);
        $this->addPrimaryKey('WITH_USER', 'WithUser', 'VARCHAR', true, 1023, null);
        $this->addPrimaryKey('WITH_SERVER', 'WithServer', 'VARCHAR', true, 1023, null);
        $this->addPrimaryKey('WITH_RESOURCE', 'WithResource', 'VARCHAR', true, 1023, null);
        $this->addColumn('SAVE', 'Save', 'TINYINT', false, 4, null);
        $this->addColumn('EXPIRE', 'Expire', 'INTEGER', false, 11, null);
        $this->addColumn('OTR', 'Otr', 'TINYINT', false, 4, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
    } // buildRelations()

} // ArchiveJidPrefsTableMap
