<?php



/**
 * This class defines the structure of the 'archive_messages' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Tue Sep 30 17:21:54 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class ArchiveMessagesTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.ArchiveMessagesTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('archive_messages');
        $this->setPhpName('ArchiveMessages');
        $this->setClassname('ArchiveMessages');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
        $this->addColumn('COLL_ID', 'CollId', 'INTEGER', true, 11, null);
        $this->addColumn('UTC', 'Utc', 'TIMESTAMP', true, null, null);
        $this->addColumn('DIR', 'Dir', 'TINYINT', false, 4, null);
        $this->addColumn('BODY', 'Body', 'LONGVARCHAR', false, null, null);
        $this->addColumn('NAME', 'Name', 'VARCHAR', false, 1023, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
    } // buildRelations()

} // ArchiveMessagesTableMap
