<?php


/**
 * Base class that represents a row from the 'archive_jid_prefs' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Tue Sep 30 17:21:54 2014
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseArchiveJidPrefs extends BaseObject implements Persistent
{
    /**
     * Peer class name
     */
    const PEER = 'ArchiveJidPrefsPeer';

    /**
     * The Peer class.
     * Instance provides a convenient way of calling static methods on a class
     * that calling code may not be able to identify.
     * @var        ArchiveJidPrefsPeer
     */
    protected static $peer;

    /**
     * The flag var to prevent infinit loop in deep copy
     * @var       boolean
     */
    protected $startCopy = false;

    /**
     * The value for the us field.
     * @var        string
     */
    protected $us;

    /**
     * The value for the with_user field.
     * @var        string
     */
    protected $with_user;

    /**
     * The value for the with_server field.
     * @var        string
     */
    protected $with_server;

    /**
     * The value for the with_resource field.
     * @var        string
     */
    protected $with_resource;

    /**
     * The value for the save field.
     * @var        int
     */
    protected $save;

    /**
     * The value for the expire field.
     * @var        int
     */
    protected $expire;

    /**
     * The value for the otr field.
     * @var        int
     */
    protected $otr;

    /**
     * Flag to prevent endless save loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInSave = false;

    /**
     * Flag to prevent endless validation loop, if this object is referenced
     * by another object which falls in this transaction.
     * @var        boolean
     */
    protected $alreadyInValidation = false;

    /**
     * Get the [us] column value.
     *
     * @return string
     */
    public function getUs()
    {
        return $this->us;
    }

    /**
     * Get the [with_user] column value.
     *
     * @return string
     */
    public function getWithUser()
    {
        return $this->with_user;
    }

    /**
     * Get the [with_server] column value.
     *
     * @return string
     */
    public function getWithServer()
    {
        return $this->with_server;
    }

    /**
     * Get the [with_resource] column value.
     *
     * @return string
     */
    public function getWithResource()
    {
        return $this->with_resource;
    }

    /**
     * Get the [save] column value.
     *
     * @return int
     */
    public function getSave()
    {
        return $this->save;
    }

    /**
     * Get the [expire] column value.
     *
     * @return int
     */
    public function getExpire()
    {
        return $this->expire;
    }

    /**
     * Get the [otr] column value.
     *
     * @return int
     */
    public function getOtr()
    {
        return $this->otr;
    }

    /**
     * Set the value of [us] column.
     *
     * @param string $v new value
     * @return ArchiveJidPrefs The current object (for fluent API support)
     */
    public function setUs($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->us !== $v) {
            $this->us = $v;
            $this->modifiedColumns[] = ArchiveJidPrefsPeer::US;
        }


        return $this;
    } // setUs()

    /**
     * Set the value of [with_user] column.
     *
     * @param string $v new value
     * @return ArchiveJidPrefs The current object (for fluent API support)
     */
    public function setWithUser($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->with_user !== $v) {
            $this->with_user = $v;
            $this->modifiedColumns[] = ArchiveJidPrefsPeer::WITH_USER;
        }


        return $this;
    } // setWithUser()

    /**
     * Set the value of [with_server] column.
     *
     * @param string $v new value
     * @return ArchiveJidPrefs The current object (for fluent API support)
     */
    public function setWithServer($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->with_server !== $v) {
            $this->with_server = $v;
            $this->modifiedColumns[] = ArchiveJidPrefsPeer::WITH_SERVER;
        }


        return $this;
    } // setWithServer()

    /**
     * Set the value of [with_resource] column.
     *
     * @param string $v new value
     * @return ArchiveJidPrefs The current object (for fluent API support)
     */
    public function setWithResource($v)
    {
        if ($v !== null) {
            $v = (string) $v;
        }

        if ($this->with_resource !== $v) {
            $this->with_resource = $v;
            $this->modifiedColumns[] = ArchiveJidPrefsPeer::WITH_RESOURCE;
        }


        return $this;
    } // setWithResource()

    /**
     * Set the value of [save] column.
     *
     * @param int $v new value
     * @return ArchiveJidPrefs The current object (for fluent API support)
     */
    public function setSave($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->save !== $v) {
            $this->save = $v;
            $this->modifiedColumns[] = ArchiveJidPrefsPeer::SAVE;
        }


        return $this;
    } // setSave()

    /**
     * Set the value of [expire] column.
     *
     * @param int $v new value
     * @return ArchiveJidPrefs The current object (for fluent API support)
     */
    public function setExpire($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->expire !== $v) {
            $this->expire = $v;
            $this->modifiedColumns[] = ArchiveJidPrefsPeer::EXPIRE;
        }


        return $this;
    } // setExpire()

    /**
     * Set the value of [otr] column.
     *
     * @param int $v new value
     * @return ArchiveJidPrefs The current object (for fluent API support)
     */
    public function setOtr($v)
    {
        if ($v !== null) {
            $v = (int) $v;
        }

        if ($this->otr !== $v) {
            $this->otr = $v;
            $this->modifiedColumns[] = ArchiveJidPrefsPeer::OTR;
        }


        return $this;
    } // setOtr()

    /**
     * Indicates whether the columns in this object are only set to default values.
     *
     * This method can be used in conjunction with isModified() to indicate whether an object is both
     * modified _and_ has some values set which are non-default.
     *
     * @return boolean Whether the columns in this object are only been set with default values.
     */
    public function hasOnlyDefaultValues()
    {
        // otherwise, everything was equal, so return true
        return true;
    } // hasOnlyDefaultValues()

    /**
     * Hydrates (populates) the object variables with values from the database resultset.
     *
     * An offset (0-based "start column") is specified so that objects can be hydrated
     * with a subset of the columns in the resultset rows.  This is needed, for example,
     * for results of JOIN queries where the resultset row includes columns from two or
     * more tables.
     *
     * @param array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
     * @param int $startcol 0-based offset column which indicates which restultset column to start with.
     * @param boolean $rehydrate Whether this object is being re-hydrated from the database.
     * @return int             next starting column
     * @throws PropelException - Any caught Exception will be rewrapped as a PropelException.
     */
    public function hydrate($row, $startcol = 0, $rehydrate = false)
    {
        try {

            $this->us = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
            $this->with_user = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
            $this->with_server = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
            $this->with_resource = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
            $this->save = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
            $this->expire = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
            $this->otr = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
            $this->resetModified();

            $this->setNew(false);

            if ($rehydrate) {
                $this->ensureConsistency();
            }

            return $startcol + 7; // 7 = ArchiveJidPrefsPeer::NUM_HYDRATE_COLUMNS.

        } catch (Exception $e) {
            throw new PropelException("Error populating ArchiveJidPrefs object", $e);
        }
    }

    /**
     * Checks and repairs the internal consistency of the object.
     *
     * This method is executed after an already-instantiated object is re-hydrated
     * from the database.  It exists to check any foreign keys to make sure that
     * the objects related to the current object are correct based on foreign key.
     *
     * You can override this method in the stub class, but you should always invoke
     * the base method from the overridden method (i.e. parent::ensureConsistency()),
     * in case your model changes.
     *
     * @throws PropelException
     */
    public function ensureConsistency()
    {

    } // ensureConsistency

    /**
     * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
     *
     * This will only work if the object has been saved and has a valid primary key set.
     *
     * @param boolean $deep (optional) Whether to also de-associated any related objects.
     * @param PropelPDO $con (optional) The PropelPDO connection to use.
     * @return void
     * @throws PropelException - if this object is deleted, unsaved or doesn't have pk match in db
     */
    public function reload($deep = false, PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("Cannot reload a deleted object.");
        }

        if ($this->isNew()) {
            throw new PropelException("Cannot reload an unsaved object.");
        }

        if ($con === null) {
            $con = Propel::getConnection(ArchiveJidPrefsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        // We don't need to alter the object instance pool; we're just modifying this instance
        // already in the pool.

        $stmt = ArchiveJidPrefsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
        $row = $stmt->fetch(PDO::FETCH_NUM);
        $stmt->closeCursor();
        if (!$row) {
            throw new PropelException('Cannot find matching row in the database to reload object values.');
        }
        $this->hydrate($row, 0, true); // rehydrate

        if ($deep) {  // also de-associate any related objects?

        } // if (deep)
    }

    /**
     * Removes this object from datastore and sets delete attribute.
     *
     * @param PropelPDO $con
     * @return void
     * @throws PropelException
     * @throws Exception
     * @see        BaseObject::setDeleted()
     * @see        BaseObject::isDeleted()
     */
    public function delete(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("This object has already been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(ArchiveJidPrefsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        try {
            $deleteQuery = ArchiveJidPrefsQuery::create()
                ->filterByPrimaryKey($this->getPrimaryKey());
            $ret = $this->preDelete($con);
            if ($ret) {
                $deleteQuery->delete($con);
                $this->postDelete($con);
                $con->commit();
                $this->setDeleted(true);
            } else {
                $con->commit();
            }
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Persists this object to the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All modified related objects will also be persisted in the doSave()
     * method.  This method wraps all precipitate database operations in a
     * single transaction.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @throws Exception
     * @see        doSave()
     */
    public function save(PropelPDO $con = null)
    {
        if ($this->isDeleted()) {
            throw new PropelException("You cannot save an object that has been deleted.");
        }

        if ($con === null) {
            $con = Propel::getConnection(ArchiveJidPrefsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $con->beginTransaction();
        $isInsert = $this->isNew();
        try {
            $ret = $this->preSave($con);
            if ($isInsert) {
                $ret = $ret && $this->preInsert($con);
            } else {
                $ret = $ret && $this->preUpdate($con);
            }
            if ($ret) {
                $affectedRows = $this->doSave($con);
                if ($isInsert) {
                    $this->postInsert($con);
                } else {
                    $this->postUpdate($con);
                }
                $this->postSave($con);
                ArchiveJidPrefsPeer::addInstanceToPool($this);
            } else {
                $affectedRows = 0;
            }
            $con->commit();

            return $affectedRows;
        } catch (Exception $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs the work of inserting or updating the row in the database.
     *
     * If the object is new, it inserts it; otherwise an update is performed.
     * All related objects are also updated in this method.
     *
     * @param PropelPDO $con
     * @return int             The number of rows affected by this insert/update and any referring fk objects' save() operations.
     * @throws PropelException
     * @see        save()
     */
    protected function doSave(PropelPDO $con)
    {
        $affectedRows = 0; // initialize var to track total num of affected rows
        if (!$this->alreadyInSave) {
            $this->alreadyInSave = true;

            if ($this->isNew() || $this->isModified()) {
                // persist changes
                if ($this->isNew()) {
                    $this->doInsert($con);
                } else {
                    $this->doUpdate($con);
                }
                $affectedRows += 1;
                $this->resetModified();
            }

            $this->alreadyInSave = false;

        }

        return $affectedRows;
    } // doSave()

    /**
     * Insert the row in the database.
     *
     * @param PropelPDO $con
     *
     * @throws PropelException
     * @see        doSave()
     */
    protected function doInsert(PropelPDO $con)
    {
        $modifiedColumns = array();
        $index = 0;


         // check the columns in natural order for more readable SQL queries
        if ($this->isColumnModified(ArchiveJidPrefsPeer::US)) {
            $modifiedColumns[':p' . $index++]  = '`US`';
        }
        if ($this->isColumnModified(ArchiveJidPrefsPeer::WITH_USER)) {
            $modifiedColumns[':p' . $index++]  = '`WITH_USER`';
        }
        if ($this->isColumnModified(ArchiveJidPrefsPeer::WITH_SERVER)) {
            $modifiedColumns[':p' . $index++]  = '`WITH_SERVER`';
        }
        if ($this->isColumnModified(ArchiveJidPrefsPeer::WITH_RESOURCE)) {
            $modifiedColumns[':p' . $index++]  = '`WITH_RESOURCE`';
        }
        if ($this->isColumnModified(ArchiveJidPrefsPeer::SAVE)) {
            $modifiedColumns[':p' . $index++]  = '`SAVE`';
        }
        if ($this->isColumnModified(ArchiveJidPrefsPeer::EXPIRE)) {
            $modifiedColumns[':p' . $index++]  = '`EXPIRE`';
        }
        if ($this->isColumnModified(ArchiveJidPrefsPeer::OTR)) {
            $modifiedColumns[':p' . $index++]  = '`OTR`';
        }

        $sql = sprintf(
            'INSERT INTO `archive_jid_prefs` (%s) VALUES (%s)',
            implode(', ', $modifiedColumns),
            implode(', ', array_keys($modifiedColumns))
        );

        try {
            $stmt = $con->prepare($sql);
            foreach ($modifiedColumns as $identifier => $columnName) {
                switch ($columnName) {
                    case '`US`':
                        $stmt->bindValue($identifier, $this->us, PDO::PARAM_STR);
                        break;
                    case '`WITH_USER`':
                        $stmt->bindValue($identifier, $this->with_user, PDO::PARAM_STR);
                        break;
                    case '`WITH_SERVER`':
                        $stmt->bindValue($identifier, $this->with_server, PDO::PARAM_STR);
                        break;
                    case '`WITH_RESOURCE`':
                        $stmt->bindValue($identifier, $this->with_resource, PDO::PARAM_STR);
                        break;
                    case '`SAVE`':
                        $stmt->bindValue($identifier, $this->save, PDO::PARAM_INT);
                        break;
                    case '`EXPIRE`':
                        $stmt->bindValue($identifier, $this->expire, PDO::PARAM_INT);
                        break;
                    case '`OTR`':
                        $stmt->bindValue($identifier, $this->otr, PDO::PARAM_INT);
                        break;
                }
            }
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute INSERT statement [%s]', $sql), $e);
        }

        $this->setNew(false);
    }

    /**
     * Update the row in the database.
     *
     * @param PropelPDO $con
     *
     * @see        doSave()
     */
    protected function doUpdate(PropelPDO $con)
    {
        $selectCriteria = $this->buildPkeyCriteria();
        $valuesCriteria = $this->buildCriteria();
        BasePeer::doUpdate($selectCriteria, $valuesCriteria, $con);
    }

    /**
     * Array of ValidationFailed objects.
     * @var        array ValidationFailed[]
     */
    protected $validationFailures = array();

    /**
     * Gets any ValidationFailed objects that resulted from last call to validate().
     *
     *
     * @return array ValidationFailed[]
     * @see        validate()
     */
    public function getValidationFailures()
    {
        return $this->validationFailures;
    }

    /**
     * Validates the objects modified field values and all objects related to this table.
     *
     * If $columns is either a column name or an array of column names
     * only those columns are validated.
     *
     * @param mixed $columns Column name or an array of column names.
     * @return boolean Whether all columns pass validation.
     * @see        doValidate()
     * @see        getValidationFailures()
     */
    public function validate($columns = null)
    {
        $res = $this->doValidate($columns);
        if ($res === true) {
            $this->validationFailures = array();

            return true;
        } else {
            $this->validationFailures = $res;

            return false;
        }
    }

    /**
     * This function performs the validation work for complex object models.
     *
     * In addition to checking the current object, all related objects will
     * also be validated.  If all pass then <code>true</code> is returned; otherwise
     * an aggreagated array of ValidationFailed objects will be returned.
     *
     * @param array $columns Array of column names to validate.
     * @return mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
     */
    protected function doValidate($columns = null)
    {
        if (!$this->alreadyInValidation) {
            $this->alreadyInValidation = true;
            $retval = null;

            $failureMap = array();


            if (($retval = ArchiveJidPrefsPeer::doValidate($this, $columns)) !== true) {
                $failureMap = array_merge($failureMap, $retval);
            }



            $this->alreadyInValidation = false;
        }

        return (!empty($failureMap) ? $failureMap : true);
    }

    /**
     * Retrieves a field from the object by name passed in as a string.
     *
     * @param string $name name
     * @param string $type The type of fieldname the $name is of:
     *               one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *               BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *               Defaults to BasePeer::TYPE_PHPNAME
     * @return mixed Value of field.
     */
    public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = ArchiveJidPrefsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
        $field = $this->getByPosition($pos);

        return $field;
    }

    /**
     * Retrieves a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @return mixed Value of field at $pos
     */
    public function getByPosition($pos)
    {
        switch ($pos) {
            case 0:
                return $this->getUs();
                break;
            case 1:
                return $this->getWithUser();
                break;
            case 2:
                return $this->getWithServer();
                break;
            case 3:
                return $this->getWithResource();
                break;
            case 4:
                return $this->getSave();
                break;
            case 5:
                return $this->getExpire();
                break;
            case 6:
                return $this->getOtr();
                break;
            default:
                return null;
                break;
        } // switch()
    }

    /**
     * Exports the object as an array.
     *
     * You can specify the key type of the array by passing one of the class
     * type constants.
     *
     * @param     string  $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     *                    BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                    Defaults to BasePeer::TYPE_PHPNAME.
     * @param     boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns. Defaults to true.
     * @param     array $alreadyDumpedObjects List of objects to skip to avoid recursion
     *
     * @return array an associative array containing the field names (as keys) and field values
     */
    public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true, $alreadyDumpedObjects = array())
    {
        if (isset($alreadyDumpedObjects['ArchiveJidPrefs'][serialize($this->getPrimaryKey())])) {
            return '*RECURSION*';
        }
        $alreadyDumpedObjects['ArchiveJidPrefs'][serialize($this->getPrimaryKey())] = true;
        $keys = ArchiveJidPrefsPeer::getFieldNames($keyType);
        $result = array(
            $keys[0] => $this->getUs(),
            $keys[1] => $this->getWithUser(),
            $keys[2] => $this->getWithServer(),
            $keys[3] => $this->getWithResource(),
            $keys[4] => $this->getSave(),
            $keys[5] => $this->getExpire(),
            $keys[6] => $this->getOtr(),
        );

        return $result;
    }

    /**
     * Sets a field from the object by name passed in as a string.
     *
     * @param string $name peer name
     * @param mixed $value field value
     * @param string $type The type of fieldname the $name is of:
     *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     *                     Defaults to BasePeer::TYPE_PHPNAME
     * @return void
     */
    public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
    {
        $pos = ArchiveJidPrefsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);

        $this->setByPosition($pos, $value);
    }

    /**
     * Sets a field from the object by Position as specified in the xml schema.
     * Zero-based.
     *
     * @param int $pos position in xml schema
     * @param mixed $value field value
     * @return void
     */
    public function setByPosition($pos, $value)
    {
        switch ($pos) {
            case 0:
                $this->setUs($value);
                break;
            case 1:
                $this->setWithUser($value);
                break;
            case 2:
                $this->setWithServer($value);
                break;
            case 3:
                $this->setWithResource($value);
                break;
            case 4:
                $this->setSave($value);
                break;
            case 5:
                $this->setExpire($value);
                break;
            case 6:
                $this->setOtr($value);
                break;
        } // switch()
    }

    /**
     * Populates the object using an array.
     *
     * This is particularly useful when populating an object from one of the
     * request arrays (e.g. $_POST).  This method goes through the column
     * names, checking to see whether a matching key exists in populated
     * array. If so the setByName() method is called for that column.
     *
     * You can specify the key type of the array by additionally passing one
     * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
     * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
     * The default key type is the column's BasePeer::TYPE_PHPNAME
     *
     * @param array  $arr     An array to populate the object from.
     * @param string $keyType The type of keys the array uses.
     * @return void
     */
    public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
    {
        $keys = ArchiveJidPrefsPeer::getFieldNames($keyType);

        if (array_key_exists($keys[0], $arr)) $this->setUs($arr[$keys[0]]);
        if (array_key_exists($keys[1], $arr)) $this->setWithUser($arr[$keys[1]]);
        if (array_key_exists($keys[2], $arr)) $this->setWithServer($arr[$keys[2]]);
        if (array_key_exists($keys[3], $arr)) $this->setWithResource($arr[$keys[3]]);
        if (array_key_exists($keys[4], $arr)) $this->setSave($arr[$keys[4]]);
        if (array_key_exists($keys[5], $arr)) $this->setExpire($arr[$keys[5]]);
        if (array_key_exists($keys[6], $arr)) $this->setOtr($arr[$keys[6]]);
    }

    /**
     * Build a Criteria object containing the values of all modified columns in this object.
     *
     * @return Criteria The Criteria object containing all modified values.
     */
    public function buildCriteria()
    {
        $criteria = new Criteria(ArchiveJidPrefsPeer::DATABASE_NAME);

        if ($this->isColumnModified(ArchiveJidPrefsPeer::US)) $criteria->add(ArchiveJidPrefsPeer::US, $this->us);
        if ($this->isColumnModified(ArchiveJidPrefsPeer::WITH_USER)) $criteria->add(ArchiveJidPrefsPeer::WITH_USER, $this->with_user);
        if ($this->isColumnModified(ArchiveJidPrefsPeer::WITH_SERVER)) $criteria->add(ArchiveJidPrefsPeer::WITH_SERVER, $this->with_server);
        if ($this->isColumnModified(ArchiveJidPrefsPeer::WITH_RESOURCE)) $criteria->add(ArchiveJidPrefsPeer::WITH_RESOURCE, $this->with_resource);
        if ($this->isColumnModified(ArchiveJidPrefsPeer::SAVE)) $criteria->add(ArchiveJidPrefsPeer::SAVE, $this->save);
        if ($this->isColumnModified(ArchiveJidPrefsPeer::EXPIRE)) $criteria->add(ArchiveJidPrefsPeer::EXPIRE, $this->expire);
        if ($this->isColumnModified(ArchiveJidPrefsPeer::OTR)) $criteria->add(ArchiveJidPrefsPeer::OTR, $this->otr);

        return $criteria;
    }

    /**
     * Builds a Criteria object containing the primary key for this object.
     *
     * Unlike buildCriteria() this method includes the primary key values regardless
     * of whether or not they have been modified.
     *
     * @return Criteria The Criteria object containing value(s) for primary key(s).
     */
    public function buildPkeyCriteria()
    {
        $criteria = new Criteria(ArchiveJidPrefsPeer::DATABASE_NAME);
        $criteria->add(ArchiveJidPrefsPeer::US, $this->us);
        $criteria->add(ArchiveJidPrefsPeer::WITH_USER, $this->with_user);
        $criteria->add(ArchiveJidPrefsPeer::WITH_SERVER, $this->with_server);
        $criteria->add(ArchiveJidPrefsPeer::WITH_RESOURCE, $this->with_resource);

        return $criteria;
    }

    /**
     * Returns the composite primary key for this object.
     * The array elements will be in same order as specified in XML.
     * @return array
     */
    public function getPrimaryKey()
    {
        $pks = array();
        $pks[0] = $this->getUs();
        $pks[1] = $this->getWithUser();
        $pks[2] = $this->getWithServer();
        $pks[3] = $this->getWithResource();

        return $pks;
    }

    /**
     * Set the [composite] primary key.
     *
     * @param array $keys The elements of the composite key (order must match the order in XML file).
     * @return void
     */
    public function setPrimaryKey($keys)
    {
        $this->setUs($keys[0]);
        $this->setWithUser($keys[1]);
        $this->setWithServer($keys[2]);
        $this->setWithResource($keys[3]);
    }

    /**
     * Returns true if the primary key for this object is null.
     * @return boolean
     */
    public function isPrimaryKeyNull()
    {

        return (null === $this->getUs()) && (null === $this->getWithUser()) && (null === $this->getWithServer()) && (null === $this->getWithResource());
    }

    /**
     * Sets contents of passed object to values from current object.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param object $copyObj An object of ArchiveJidPrefs (or compatible) type.
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @param boolean $makeNew Whether to reset autoincrement PKs and make the object new.
     * @throws PropelException
     */
    public function copyInto($copyObj, $deepCopy = false, $makeNew = true)
    {
        $copyObj->setUs($this->getUs());
        $copyObj->setWithUser($this->getWithUser());
        $copyObj->setWithServer($this->getWithServer());
        $copyObj->setWithResource($this->getWithResource());
        $copyObj->setSave($this->getSave());
        $copyObj->setExpire($this->getExpire());
        $copyObj->setOtr($this->getOtr());
        if ($makeNew) {
            $copyObj->setNew(true);
        }
    }

    /**
     * Makes a copy of this object that will be inserted as a new row in table when saved.
     * It creates a new object filling in the simple attributes, but skipping any primary
     * keys that are defined for the table.
     *
     * If desired, this method can also make copies of all associated (fkey referrers)
     * objects.
     *
     * @param boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
     * @return ArchiveJidPrefs Clone of current object.
     * @throws PropelException
     */
    public function copy($deepCopy = false)
    {
        // we use get_class(), because this might be a subclass
        $clazz = get_class($this);
        $copyObj = new $clazz();
        $this->copyInto($copyObj, $deepCopy);

        return $copyObj;
    }

    /**
     * Returns a peer instance associated with this om.
     *
     * Since Peer classes are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     *
     * @return ArchiveJidPrefsPeer
     */
    public function getPeer()
    {
        if (self::$peer === null) {
            self::$peer = new ArchiveJidPrefsPeer();
        }

        return self::$peer;
    }

    /**
     * Clears the current object and sets all attributes to their default values
     */
    public function clear()
    {
        $this->us = null;
        $this->with_user = null;
        $this->with_server = null;
        $this->with_resource = null;
        $this->save = null;
        $this->expire = null;
        $this->otr = null;
        $this->alreadyInSave = false;
        $this->alreadyInValidation = false;
        $this->clearAllReferences();
        $this->resetModified();
        $this->setNew(true);
        $this->setDeleted(false);
    }

    /**
     * Resets all references to other model objects or collections of model objects.
     *
     * This method is a user-space workaround for PHP's inability to garbage collect
     * objects with circular references (even in PHP 5.3). This is currently necessary
     * when using Propel in certain daemon or large-volumne/high-memory operations.
     *
     * @param boolean $deep Whether to also clear the references on all referrer objects.
     */
    public function clearAllReferences($deep = false)
    {
        if ($deep) {
        } // if ($deep)

    }

    /**
     * return the string representation of this object
     *
     * @return string
     */
    public function __toString()
    {
        return (string) $this->exportTo(ArchiveJidPrefsPeer::DEFAULT_STRING_FORMAT);
    }

    /**
     * return true is the object is in saving state
     *
     * @return boolean
     */
    public function isAlreadyInSave()
    {
        return $this->alreadyInSave;
    }

}
