<?php


/**
 * Base static class for performing query and update operations on the 'archive_collections' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Tue Sep 30 17:21:54 2014
 *
 * @package propel.generator.lib.model.om
 */
abstract class BaseArchiveCollectionsPeer
{

    /** the default database name for this class */
    const DATABASE_NAME = 'propel';

    /** the table name for this class */
    const TABLE_NAME = 'archive_collections';

    /** the related Propel class for this table */
    const OM_CLASS = 'ArchiveCollections';

    /** the related TableMap class for this table */
    const TM_CLASS = 'ArchiveCollectionsTableMap';

    /** The total number of columns. */
    const NUM_COLUMNS = 15;

    /** The number of lazy-loaded columns. */
    const NUM_LAZY_LOAD_COLUMNS = 0;

    /** The number of columns to hydrate (NUM_COLUMNS - NUM_LAZY_LOAD_COLUMNS) */
    const NUM_HYDRATE_COLUMNS = 15;

    /** the column name for the ID field */
    const ID = 'archive_collections.ID';

    /** the column name for the PREV_ID field */
    const PREV_ID = 'archive_collections.PREV_ID';

    /** the column name for the NEXT_ID field */
    const NEXT_ID = 'archive_collections.NEXT_ID';

    /** the column name for the US field */
    const US = 'archive_collections.US';

    /** the column name for the WITH_USER field */
    const WITH_USER = 'archive_collections.WITH_USER';

    /** the column name for the WITH_SERVER field */
    const WITH_SERVER = 'archive_collections.WITH_SERVER';

    /** the column name for the WITH_RESOURCE field */
    const WITH_RESOURCE = 'archive_collections.WITH_RESOURCE';

    /** the column name for the UTC field */
    const UTC = 'archive_collections.UTC';

    /** the column name for the CHANGE_BY field */
    const CHANGE_BY = 'archive_collections.CHANGE_BY';

    /** the column name for the CHANGE_UTC field */
    const CHANGE_UTC = 'archive_collections.CHANGE_UTC';

    /** the column name for the DELETED field */
    const DELETED = 'archive_collections.DELETED';

    /** the column name for the SUBJECT field */
    const SUBJECT = 'archive_collections.SUBJECT';

    /** the column name for the THREAD field */
    const THREAD = 'archive_collections.THREAD';

    /** the column name for the CRYPT field */
    const CRYPT = 'archive_collections.CRYPT';

    /** the column name for the EXTRA field */
    const EXTRA = 'archive_collections.EXTRA';

    /** The default string format for model objects of the related table **/
    const DEFAULT_STRING_FORMAT = 'YAML';

    /**
     * An identiy map to hold any loaded instances of ArchiveCollections objects.
     * This must be public so that other peer classes can access this when hydrating from JOIN
     * queries.
     * @var        array ArchiveCollections[]
     */
    public static $instances = array();


    /**
     * holds an array of fieldnames
     *
     * first dimension keys are the type constants
     * e.g. ArchiveCollectionsPeer::$fieldNames[ArchiveCollectionsPeer::TYPE_PHPNAME][0] = 'Id'
     */
    protected static $fieldNames = array (
        BasePeer::TYPE_PHPNAME => array ('Id', 'PrevId', 'NextId', 'Us', 'WithUser', 'WithServer', 'WithResource', 'Utc', 'ChangeBy', 'ChangeUtc', 'Deleted', 'Subject', 'Thread', 'Crypt', 'Extra', ),
        BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'prevId', 'nextId', 'us', 'withUser', 'withServer', 'withResource', 'utc', 'changeBy', 'changeUtc', 'deleted', 'subject', 'thread', 'crypt', 'extra', ),
        BasePeer::TYPE_COLNAME => array (ArchiveCollectionsPeer::ID, ArchiveCollectionsPeer::PREV_ID, ArchiveCollectionsPeer::NEXT_ID, ArchiveCollectionsPeer::US, ArchiveCollectionsPeer::WITH_USER, ArchiveCollectionsPeer::WITH_SERVER, ArchiveCollectionsPeer::WITH_RESOURCE, ArchiveCollectionsPeer::UTC, ArchiveCollectionsPeer::CHANGE_BY, ArchiveCollectionsPeer::CHANGE_UTC, ArchiveCollectionsPeer::DELETED, ArchiveCollectionsPeer::SUBJECT, ArchiveCollectionsPeer::THREAD, ArchiveCollectionsPeer::CRYPT, ArchiveCollectionsPeer::EXTRA, ),
        BasePeer::TYPE_RAW_COLNAME => array ('ID', 'PREV_ID', 'NEXT_ID', 'US', 'WITH_USER', 'WITH_SERVER', 'WITH_RESOURCE', 'UTC', 'CHANGE_BY', 'CHANGE_UTC', 'DELETED', 'SUBJECT', 'THREAD', 'CRYPT', 'EXTRA', ),
        BasePeer::TYPE_FIELDNAME => array ('id', 'prev_id', 'next_id', 'us', 'with_user', 'with_server', 'with_resource', 'utc', 'change_by', 'change_utc', 'deleted', 'subject', 'thread', 'crypt', 'extra', ),
        BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, )
    );

    /**
     * holds an array of keys for quick access to the fieldnames array
     *
     * first dimension keys are the type constants
     * e.g. ArchiveCollectionsPeer::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
     */
    protected static $fieldKeys = array (
        BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'PrevId' => 1, 'NextId' => 2, 'Us' => 3, 'WithUser' => 4, 'WithServer' => 5, 'WithResource' => 6, 'Utc' => 7, 'ChangeBy' => 8, 'ChangeUtc' => 9, 'Deleted' => 10, 'Subject' => 11, 'Thread' => 12, 'Crypt' => 13, 'Extra' => 14, ),
        BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'prevId' => 1, 'nextId' => 2, 'us' => 3, 'withUser' => 4, 'withServer' => 5, 'withResource' => 6, 'utc' => 7, 'changeBy' => 8, 'changeUtc' => 9, 'deleted' => 10, 'subject' => 11, 'thread' => 12, 'crypt' => 13, 'extra' => 14, ),
        BasePeer::TYPE_COLNAME => array (ArchiveCollectionsPeer::ID => 0, ArchiveCollectionsPeer::PREV_ID => 1, ArchiveCollectionsPeer::NEXT_ID => 2, ArchiveCollectionsPeer::US => 3, ArchiveCollectionsPeer::WITH_USER => 4, ArchiveCollectionsPeer::WITH_SERVER => 5, ArchiveCollectionsPeer::WITH_RESOURCE => 6, ArchiveCollectionsPeer::UTC => 7, ArchiveCollectionsPeer::CHANGE_BY => 8, ArchiveCollectionsPeer::CHANGE_UTC => 9, ArchiveCollectionsPeer::DELETED => 10, ArchiveCollectionsPeer::SUBJECT => 11, ArchiveCollectionsPeer::THREAD => 12, ArchiveCollectionsPeer::CRYPT => 13, ArchiveCollectionsPeer::EXTRA => 14, ),
        BasePeer::TYPE_RAW_COLNAME => array ('ID' => 0, 'PREV_ID' => 1, 'NEXT_ID' => 2, 'US' => 3, 'WITH_USER' => 4, 'WITH_SERVER' => 5, 'WITH_RESOURCE' => 6, 'UTC' => 7, 'CHANGE_BY' => 8, 'CHANGE_UTC' => 9, 'DELETED' => 10, 'SUBJECT' => 11, 'THREAD' => 12, 'CRYPT' => 13, 'EXTRA' => 14, ),
        BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'prev_id' => 1, 'next_id' => 2, 'us' => 3, 'with_user' => 4, 'with_server' => 5, 'with_resource' => 6, 'utc' => 7, 'change_by' => 8, 'change_utc' => 9, 'deleted' => 10, 'subject' => 11, 'thread' => 12, 'crypt' => 13, 'extra' => 14, ),
        BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, )
    );

    /**
     * Translates a fieldname to another type
     *
     * @param      string $name field name
     * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
     * @param      string $toType   One of the class type constants
     * @return string          translated name of the field.
     * @throws PropelException - if the specified name could not be found in the fieldname mappings.
     */
    public static function translateFieldName($name, $fromType, $toType)
    {
        $toNames = ArchiveCollectionsPeer::getFieldNames($toType);
        $key = isset(ArchiveCollectionsPeer::$fieldKeys[$fromType][$name]) ? ArchiveCollectionsPeer::$fieldKeys[$fromType][$name] : null;
        if ($key === null) {
            throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(ArchiveCollectionsPeer::$fieldKeys[$fromType], true));
        }

        return $toNames[$key];
    }

    /**
     * Returns an array of field names.
     *
     * @param      string $type The type of fieldnames to return:
     *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
     *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
     * @return array           A list of field names
     * @throws PropelException - if the type is not valid.
     */
    public static function getFieldNames($type = BasePeer::TYPE_PHPNAME)
    {
        if (!array_key_exists($type, ArchiveCollectionsPeer::$fieldNames)) {
            throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
        }

        return ArchiveCollectionsPeer::$fieldNames[$type];
    }

    /**
     * Convenience method which changes table.column to alias.column.
     *
     * Using this method you can maintain SQL abstraction while using column aliases.
     * <code>
     *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
     *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
     * </code>
     * @param      string $alias The alias for the current table.
     * @param      string $column The column name for current table. (i.e. ArchiveCollectionsPeer::COLUMN_NAME).
     * @return string
     */
    public static function alias($alias, $column)
    {
        return str_replace(ArchiveCollectionsPeer::TABLE_NAME.'.', $alias.'.', $column);
    }

    /**
     * Add all the columns needed to create a new object.
     *
     * Note: any columns that were marked with lazyLoad="true" in the
     * XML schema will not be added to the select list and only loaded
     * on demand.
     *
     * @param      Criteria $criteria object containing the columns to add.
     * @param      string   $alias    optional table alias
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function addSelectColumns(Criteria $criteria, $alias = null)
    {
        if (null === $alias) {
            $criteria->addSelectColumn(ArchiveCollectionsPeer::ID);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::PREV_ID);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::NEXT_ID);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::US);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::WITH_USER);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::WITH_SERVER);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::WITH_RESOURCE);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::UTC);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::CHANGE_BY);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::CHANGE_UTC);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::DELETED);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::SUBJECT);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::THREAD);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::CRYPT);
            $criteria->addSelectColumn(ArchiveCollectionsPeer::EXTRA);
        } else {
            $criteria->addSelectColumn($alias . '.ID');
            $criteria->addSelectColumn($alias . '.PREV_ID');
            $criteria->addSelectColumn($alias . '.NEXT_ID');
            $criteria->addSelectColumn($alias . '.US');
            $criteria->addSelectColumn($alias . '.WITH_USER');
            $criteria->addSelectColumn($alias . '.WITH_SERVER');
            $criteria->addSelectColumn($alias . '.WITH_RESOURCE');
            $criteria->addSelectColumn($alias . '.UTC');
            $criteria->addSelectColumn($alias . '.CHANGE_BY');
            $criteria->addSelectColumn($alias . '.CHANGE_UTC');
            $criteria->addSelectColumn($alias . '.DELETED');
            $criteria->addSelectColumn($alias . '.SUBJECT');
            $criteria->addSelectColumn($alias . '.THREAD');
            $criteria->addSelectColumn($alias . '.CRYPT');
            $criteria->addSelectColumn($alias . '.EXTRA');
        }
    }

    /**
     * Returns the number of rows matching criteria.
     *
     * @param      Criteria $criteria
     * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
     * @param      PropelPDO $con
     * @return int Number of matching rows.
     */
    public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
    {
        // we may modify criteria, so copy it first
        $criteria = clone $criteria;

        // We need to set the primary table name, since in the case that there are no WHERE columns
        // it will be impossible for the BasePeer::createSelectSql() method to determine which
        // tables go into the FROM clause.
        $criteria->setPrimaryTableName(ArchiveCollectionsPeer::TABLE_NAME);

        if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
            $criteria->setDistinct();
        }

        if (!$criteria->hasSelectClause()) {
            ArchiveCollectionsPeer::addSelectColumns($criteria);
        }

        $criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
        $criteria->setDbName(ArchiveCollectionsPeer::DATABASE_NAME); // Set the correct dbName

        if ($con === null) {
            $con = Propel::getConnection(ArchiveCollectionsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        // BasePeer returns a PDOStatement
        $stmt = BasePeer::doCount($criteria, $con);

        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $count = (int) $row[0];
        } else {
            $count = 0; // no rows returned; we infer that means 0 matches.
        }
        $stmt->closeCursor();

        return $count;
    }
    /**
     * Selects one object from the DB.
     *
     * @param      Criteria $criteria object used to create the SELECT statement.
     * @param      PropelPDO $con
     * @return                 ArchiveCollections
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
    {
        $critcopy = clone $criteria;
        $critcopy->setLimit(1);
        $objects = ArchiveCollectionsPeer::doSelect($critcopy, $con);
        if ($objects) {
            return $objects[0];
        }

        return null;
    }
    /**
     * Selects several row from the DB.
     *
     * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
     * @param      PropelPDO $con
     * @return array           Array of selected Objects
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doSelect(Criteria $criteria, PropelPDO $con = null)
    {
        return ArchiveCollectionsPeer::populateObjects(ArchiveCollectionsPeer::doSelectStmt($criteria, $con));
    }
    /**
     * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
     *
     * Use this method directly if you want to work with an executed statement durirectly (for example
     * to perform your own object hydration).
     *
     * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
     * @param      PropelPDO $con The connection to use
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     * @return PDOStatement The executed PDOStatement object.
     * @see        BasePeer::doSelect()
     */
    public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(ArchiveCollectionsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        if (!$criteria->hasSelectClause()) {
            $criteria = clone $criteria;
            ArchiveCollectionsPeer::addSelectColumns($criteria);
        }

        // Set the correct dbName
        $criteria->setDbName(ArchiveCollectionsPeer::DATABASE_NAME);

        // BasePeer returns a PDOStatement
        return BasePeer::doSelect($criteria, $con);
    }
    /**
     * Adds an object to the instance pool.
     *
     * Propel keeps cached copies of objects in an instance pool when they are retrieved
     * from the database.  In some cases -- especially when you override doSelect*()
     * methods in your stub classes -- you may need to explicitly add objects
     * to the cache in order to ensure that the same objects are always returned by doSelect*()
     * and retrieveByPK*() calls.
     *
     * @param      ArchiveCollections $obj A ArchiveCollections object.
     * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
     */
    public static function addInstanceToPool($obj, $key = null)
    {
        if (Propel::isInstancePoolingEnabled()) {
            if ($key === null) {
                $key = (string) $obj->getId();
            } // if key === null
            ArchiveCollectionsPeer::$instances[$key] = $obj;
        }
    }

    /**
     * Removes an object from the instance pool.
     *
     * Propel keeps cached copies of objects in an instance pool when they are retrieved
     * from the database.  In some cases -- especially when you override doDelete
     * methods in your stub classes -- you may need to explicitly remove objects
     * from the cache in order to prevent returning objects that no longer exist.
     *
     * @param      mixed $value A ArchiveCollections object or a primary key value.
     *
     * @return void
     * @throws PropelException - if the value is invalid.
     */
    public static function removeInstanceFromPool($value)
    {
        if (Propel::isInstancePoolingEnabled() && $value !== null) {
            if (is_object($value) && $value instanceof ArchiveCollections) {
                $key = (string) $value->getId();
            } elseif (is_scalar($value)) {
                // assume we've been passed a primary key
                $key = (string) $value;
            } else {
                $e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or ArchiveCollections object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
                throw $e;
            }

            unset(ArchiveCollectionsPeer::$instances[$key]);
        }
    } // removeInstanceFromPool()

    /**
     * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
     *
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, a serialize()d version of the primary key will be returned.
     *
     * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
     * @return   ArchiveCollections Found object or null if 1) no instance exists for specified key or 2) instance pooling has been disabled.
     * @see        getPrimaryKeyHash()
     */
    public static function getInstanceFromPool($key)
    {
        if (Propel::isInstancePoolingEnabled()) {
            if (isset(ArchiveCollectionsPeer::$instances[$key])) {
                return ArchiveCollectionsPeer::$instances[$key];
            }
        }

        return null; // just to be explicit
    }

    /**
     * Clear the instance pool.
     *
     * @return void
     */
    public static function clearInstancePool()
    {
        ArchiveCollectionsPeer::$instances = array();
    }

    /**
     * Method to invalidate the instance pool of all tables related to archive_collections
     * by a foreign key with ON DELETE CASCADE
     */
    public static function clearRelatedInstancePool()
    {
    }

    /**
     * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
     *
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, a serialize()d version of the primary key will be returned.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @return string A string version of PK or null if the components of primary key in result array are all null.
     */
    public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
    {
        // If the PK cannot be derived from the row, return null.
        if ($row[$startcol] === null) {
            return null;
        }

        return (string) $row[$startcol];
    }

    /**
     * Retrieves the primary key from the DB resultset row
     * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
     * a multi-column primary key, an array of the primary key columns will be returned.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @return mixed The primary key of the row
     */
    public static function getPrimaryKeyFromRow($row, $startcol = 0)
    {

        return (int) $row[$startcol];
    }

    /**
     * The returned array will contain objects of the default type or
     * objects that inherit from the default.
     *
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function populateObjects(PDOStatement $stmt)
    {
        $results = array();

        // set the class once to avoid overhead in the loop
        $cls = ArchiveCollectionsPeer::getOMClass();
        // populate the object(s)
        while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $key = ArchiveCollectionsPeer::getPrimaryKeyHashFromRow($row, 0);
            if (null !== ($obj = ArchiveCollectionsPeer::getInstanceFromPool($key))) {
                // We no longer rehydrate the object, since this can cause data loss.
                // See http://www.propelorm.org/ticket/509
                // $obj->hydrate($row, 0, true); // rehydrate
                $results[] = $obj;
            } else {
                $obj = new $cls();
                $obj->hydrate($row);
                $results[] = $obj;
                ArchiveCollectionsPeer::addInstanceToPool($obj, $key);
            } // if key exists
        }
        $stmt->closeCursor();

        return $results;
    }
    /**
     * Populates an object of the default type or an object that inherit from the default.
     *
     * @param      array $row PropelPDO resultset row.
     * @param      int $startcol The 0-based offset for reading from the resultset row.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     * @return array (ArchiveCollections object, last column rank)
     */
    public static function populateObject($row, $startcol = 0)
    {
        $key = ArchiveCollectionsPeer::getPrimaryKeyHashFromRow($row, $startcol);
        if (null !== ($obj = ArchiveCollectionsPeer::getInstanceFromPool($key))) {
            // We no longer rehydrate the object, since this can cause data loss.
            // See http://www.propelorm.org/ticket/509
            // $obj->hydrate($row, $startcol, true); // rehydrate
            $col = $startcol + ArchiveCollectionsPeer::NUM_HYDRATE_COLUMNS;
        } else {
            $cls = ArchiveCollectionsPeer::OM_CLASS;
            $obj = new $cls();
            $col = $obj->hydrate($row, $startcol);
            ArchiveCollectionsPeer::addInstanceToPool($obj, $key);
        }

        return array($obj, $col);
    }

    /**
     * Returns the TableMap related to this peer.
     * This method is not needed for general use but a specific application could have a need.
     * @return TableMap
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function getTableMap()
    {
        return Propel::getDatabaseMap(ArchiveCollectionsPeer::DATABASE_NAME)->getTable(ArchiveCollectionsPeer::TABLE_NAME);
    }

    /**
     * Add a TableMap instance to the database for this peer class.
     */
    public static function buildTableMap()
    {
      $dbMap = Propel::getDatabaseMap(BaseArchiveCollectionsPeer::DATABASE_NAME);
      if (!$dbMap->hasTable(BaseArchiveCollectionsPeer::TABLE_NAME)) {
        $dbMap->addTableObject(new ArchiveCollectionsTableMap());
      }
    }

    /**
     * The class that the Peer will make instances of.
     *
     *
     * @return string ClassName
     */
    public static function getOMClass()
    {
        return ArchiveCollectionsPeer::OM_CLASS;
    }

    /**
     * Performs an INSERT on the database, given a ArchiveCollections or Criteria object.
     *
     * @param      mixed $values Criteria or ArchiveCollections object containing data that is used to create the INSERT statement.
     * @param      PropelPDO $con the PropelPDO connection to use
     * @return mixed           The new primary key.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doInsert($values, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(ArchiveCollectionsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        if ($values instanceof Criteria) {
            $criteria = clone $values; // rename for clarity
        } else {
            $criteria = $values->buildCriteria(); // build Criteria from ArchiveCollections object
        }

        if ($criteria->containsKey(ArchiveCollectionsPeer::ID) && $criteria->keyContainsValue(ArchiveCollectionsPeer::ID) ) {
            throw new PropelException('Cannot insert a value for auto-increment primary key ('.ArchiveCollectionsPeer::ID.')');
        }


        // Set the correct dbName
        $criteria->setDbName(ArchiveCollectionsPeer::DATABASE_NAME);

        try {
            // use transaction because $criteria could contain info
            // for more than one table (I guess, conceivably)
            $con->beginTransaction();
            $pk = BasePeer::doInsert($criteria, $con);
            $con->commit();
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }

        return $pk;
    }

    /**
     * Performs an UPDATE on the database, given a ArchiveCollections or Criteria object.
     *
     * @param      mixed $values Criteria or ArchiveCollections object containing data that is used to create the UPDATE statement.
     * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
     * @return int             The number of affected rows (if supported by underlying database driver).
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function doUpdate($values, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(ArchiveCollectionsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        $selectCriteria = new Criteria(ArchiveCollectionsPeer::DATABASE_NAME);

        if ($values instanceof Criteria) {
            $criteria = clone $values; // rename for clarity

            $comparison = $criteria->getComparison(ArchiveCollectionsPeer::ID);
            $value = $criteria->remove(ArchiveCollectionsPeer::ID);
            if ($value) {
                $selectCriteria->add(ArchiveCollectionsPeer::ID, $value, $comparison);
            } else {
                $selectCriteria->setPrimaryTableName(ArchiveCollectionsPeer::TABLE_NAME);
            }

        } else { // $values is ArchiveCollections object
            $criteria = $values->buildCriteria(); // gets full criteria
            $selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
        }

        // set the correct dbName
        $criteria->setDbName(ArchiveCollectionsPeer::DATABASE_NAME);

        return BasePeer::doUpdate($selectCriteria, $criteria, $con);
    }

    /**
     * Deletes all rows from the archive_collections table.
     *
     * @param      PropelPDO $con the connection to use
     * @return int             The number of affected rows (if supported by underlying database driver).
     * @throws PropelException
     */
    public static function doDeleteAll(PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(ArchiveCollectionsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }
        $affectedRows = 0; // initialize var to track total num of affected rows
        try {
            // use transaction because $criteria could contain info
            // for more than one table or we could emulating ON DELETE CASCADE, etc.
            $con->beginTransaction();
            $affectedRows += BasePeer::doDeleteAll(ArchiveCollectionsPeer::TABLE_NAME, $con, ArchiveCollectionsPeer::DATABASE_NAME);
            // Because this db requires some delete cascade/set null emulation, we have to
            // clear the cached instance *after* the emulation has happened (since
            // instances get re-added by the select statement contained therein).
            ArchiveCollectionsPeer::clearInstancePool();
            ArchiveCollectionsPeer::clearRelatedInstancePool();
            $con->commit();

            return $affectedRows;
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Performs a DELETE on the database, given a ArchiveCollections or Criteria object OR a primary key value.
     *
     * @param      mixed $values Criteria or ArchiveCollections object or primary key or array of primary keys
     *              which is used to create the DELETE statement
     * @param      PropelPDO $con the connection to use
     * @return int The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
     *				if supported by native driver or if emulated using Propel.
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
     public static function doDelete($values, PropelPDO $con = null)
     {
        if ($con === null) {
            $con = Propel::getConnection(ArchiveCollectionsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
        }

        if ($values instanceof Criteria) {
            // invalidate the cache for all objects of this type, since we have no
            // way of knowing (without running a query) what objects should be invalidated
            // from the cache based on this Criteria.
            ArchiveCollectionsPeer::clearInstancePool();
            // rename for clarity
            $criteria = clone $values;
        } elseif ($values instanceof ArchiveCollections) { // it's a model object
            // invalidate the cache for this single object
            ArchiveCollectionsPeer::removeInstanceFromPool($values);
            // create criteria based on pk values
            $criteria = $values->buildPkeyCriteria();
        } else { // it's a primary key, or an array of pks
            $criteria = new Criteria(ArchiveCollectionsPeer::DATABASE_NAME);
            $criteria->add(ArchiveCollectionsPeer::ID, (array) $values, Criteria::IN);
            // invalidate the cache for this object(s)
            foreach ((array) $values as $singleval) {
                ArchiveCollectionsPeer::removeInstanceFromPool($singleval);
            }
        }

        // Set the correct dbName
        $criteria->setDbName(ArchiveCollectionsPeer::DATABASE_NAME);

        $affectedRows = 0; // initialize var to track total num of affected rows

        try {
            // use transaction because $criteria could contain info
            // for more than one table or we could emulating ON DELETE CASCADE, etc.
            $con->beginTransaction();

            $affectedRows += BasePeer::doDelete($criteria, $con);
            ArchiveCollectionsPeer::clearRelatedInstancePool();
            $con->commit();

            return $affectedRows;
        } catch (PropelException $e) {
            $con->rollBack();
            throw $e;
        }
    }

    /**
     * Validates all modified columns of given ArchiveCollections object.
     * If parameter $columns is either a single column name or an array of column names
     * than only those columns are validated.
     *
     * NOTICE: This does not apply to primary or foreign keys for now.
     *
     * @param      ArchiveCollections $obj The object to validate.
     * @param      mixed $cols Column name or array of column names.
     *
     * @return mixed TRUE if all columns are valid or the error message of the first invalid column.
     */
    public static function doValidate($obj, $cols = null)
    {
        $columns = array();

        if ($cols) {
            $dbMap = Propel::getDatabaseMap(ArchiveCollectionsPeer::DATABASE_NAME);
            $tableMap = $dbMap->getTable(ArchiveCollectionsPeer::TABLE_NAME);

            if (! is_array($cols)) {
                $cols = array($cols);
            }

            foreach ($cols as $colName) {
                if ($tableMap->hasColumn($colName)) {
                    $get = 'get' . $tableMap->getColumn($colName)->getPhpName();
                    $columns[$colName] = $obj->$get();
                }
            }
        } else {

        }

        return BasePeer::doValidate(ArchiveCollectionsPeer::DATABASE_NAME, ArchiveCollectionsPeer::TABLE_NAME, $columns);
    }

    /**
     * Retrieve a single object by pkey.
     *
     * @param      int $pk the primary key.
     * @param      PropelPDO $con the connection to use
     * @return ArchiveCollections
     */
    public static function retrieveByPK($pk, PropelPDO $con = null)
    {

        if (null !== ($obj = ArchiveCollectionsPeer::getInstanceFromPool((string) $pk))) {
            return $obj;
        }

        if ($con === null) {
            $con = Propel::getConnection(ArchiveCollectionsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $criteria = new Criteria(ArchiveCollectionsPeer::DATABASE_NAME);
        $criteria->add(ArchiveCollectionsPeer::ID, $pk);

        $v = ArchiveCollectionsPeer::doSelect($criteria, $con);

        return !empty($v) > 0 ? $v[0] : null;
    }

    /**
     * Retrieve multiple objects by pkey.
     *
     * @param      array $pks List of primary keys
     * @param      PropelPDO $con the connection to use
     * @return ArchiveCollections[]
     * @throws PropelException Any exceptions caught during processing will be
     *		 rethrown wrapped into a PropelException.
     */
    public static function retrieveByPKs($pks, PropelPDO $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection(ArchiveCollectionsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }

        $objs = null;
        if (empty($pks)) {
            $objs = array();
        } else {
            $criteria = new Criteria(ArchiveCollectionsPeer::DATABASE_NAME);
            $criteria->add(ArchiveCollectionsPeer::ID, $pks, Criteria::IN);
            $objs = ArchiveCollectionsPeer::doSelect($criteria, $con);
        }

        return $objs;
    }

} // BaseArchiveCollectionsPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseArchiveCollectionsPeer::buildTableMap();

