<?php


/**
 * Base class that represents a query for the 'archive_messages' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Tue Sep 30 17:21:54 2014
 *
 * @method ArchiveMessagesQuery orderById($order = Criteria::ASC) Order by the id column
 * @method ArchiveMessagesQuery orderByCollId($order = Criteria::ASC) Order by the coll_id column
 * @method ArchiveMessagesQuery orderByUtc($order = Criteria::ASC) Order by the utc column
 * @method ArchiveMessagesQuery orderByDir($order = Criteria::ASC) Order by the dir column
 * @method ArchiveMessagesQuery orderByBody($order = Criteria::ASC) Order by the body column
 * @method ArchiveMessagesQuery orderByName($order = Criteria::ASC) Order by the name column
 *
 * @method ArchiveMessagesQuery groupById() Group by the id column
 * @method ArchiveMessagesQuery groupByCollId() Group by the coll_id column
 * @method ArchiveMessagesQuery groupByUtc() Group by the utc column
 * @method ArchiveMessagesQuery groupByDir() Group by the dir column
 * @method ArchiveMessagesQuery groupByBody() Group by the body column
 * @method ArchiveMessagesQuery groupByName() Group by the name column
 *
 * @method ArchiveMessagesQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method ArchiveMessagesQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method ArchiveMessagesQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method ArchiveMessages findOne(PropelPDO $con = null) Return the first ArchiveMessages matching the query
 * @method ArchiveMessages findOneOrCreate(PropelPDO $con = null) Return the first ArchiveMessages matching the query, or a new ArchiveMessages object populated from the query conditions when no match is found
 *
 * @method ArchiveMessages findOneById(int $id) Return the first ArchiveMessages filtered by the id column
 * @method ArchiveMessages findOneByCollId(int $coll_id) Return the first ArchiveMessages filtered by the coll_id column
 * @method ArchiveMessages findOneByUtc(string $utc) Return the first ArchiveMessages filtered by the utc column
 * @method ArchiveMessages findOneByDir(int $dir) Return the first ArchiveMessages filtered by the dir column
 * @method ArchiveMessages findOneByBody(string $body) Return the first ArchiveMessages filtered by the body column
 * @method ArchiveMessages findOneByName(string $name) Return the first ArchiveMessages filtered by the name column
 *
 * @method array findById(int $id) Return ArchiveMessages objects filtered by the id column
 * @method array findByCollId(int $coll_id) Return ArchiveMessages objects filtered by the coll_id column
 * @method array findByUtc(string $utc) Return ArchiveMessages objects filtered by the utc column
 * @method array findByDir(int $dir) Return ArchiveMessages objects filtered by the dir column
 * @method array findByBody(string $body) Return ArchiveMessages objects filtered by the body column
 * @method array findByName(string $name) Return ArchiveMessages objects filtered by the name column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseArchiveMessagesQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseArchiveMessagesQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'ArchiveMessages', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new ArchiveMessagesQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     ArchiveMessagesQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return ArchiveMessagesQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof ArchiveMessagesQuery) {
            return $criteria;
        }
        $query = new ArchiveMessagesQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   ArchiveMessages|ArchiveMessages[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = ArchiveMessagesPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(ArchiveMessagesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   ArchiveMessages A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `COLL_ID`, `UTC`, `DIR`, `BODY`, `NAME` FROM `archive_messages` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new ArchiveMessages();
            $obj->hydrate($row);
            ArchiveMessagesPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return ArchiveMessages|ArchiveMessages[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|ArchiveMessages[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return ArchiveMessagesQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(ArchiveMessagesPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return ArchiveMessagesQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(ArchiveMessagesPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArchiveMessagesQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(ArchiveMessagesPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the coll_id column
     *
     * Example usage:
     * <code>
     * $query->filterByCollId(1234); // WHERE coll_id = 1234
     * $query->filterByCollId(array(12, 34)); // WHERE coll_id IN (12, 34)
     * $query->filterByCollId(array('min' => 12)); // WHERE coll_id > 12
     * </code>
     *
     * @param     mixed $collId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArchiveMessagesQuery The current query, for fluid interface
     */
    public function filterByCollId($collId = null, $comparison = null)
    {
        if (is_array($collId)) {
            $useMinMax = false;
            if (isset($collId['min'])) {
                $this->addUsingAlias(ArchiveMessagesPeer::COLL_ID, $collId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($collId['max'])) {
                $this->addUsingAlias(ArchiveMessagesPeer::COLL_ID, $collId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArchiveMessagesPeer::COLL_ID, $collId, $comparison);
    }

    /**
     * Filter the query on the utc column
     *
     * Example usage:
     * <code>
     * $query->filterByUtc('2011-03-14'); // WHERE utc = '2011-03-14'
     * $query->filterByUtc('now'); // WHERE utc = '2011-03-14'
     * $query->filterByUtc(array('max' => 'yesterday')); // WHERE utc > '2011-03-13'
     * </code>
     *
     * @param     mixed $utc The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArchiveMessagesQuery The current query, for fluid interface
     */
    public function filterByUtc($utc = null, $comparison = null)
    {
        if (is_array($utc)) {
            $useMinMax = false;
            if (isset($utc['min'])) {
                $this->addUsingAlias(ArchiveMessagesPeer::UTC, $utc['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($utc['max'])) {
                $this->addUsingAlias(ArchiveMessagesPeer::UTC, $utc['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArchiveMessagesPeer::UTC, $utc, $comparison);
    }

    /**
     * Filter the query on the dir column
     *
     * Example usage:
     * <code>
     * $query->filterByDir(1234); // WHERE dir = 1234
     * $query->filterByDir(array(12, 34)); // WHERE dir IN (12, 34)
     * $query->filterByDir(array('min' => 12)); // WHERE dir > 12
     * </code>
     *
     * @param     mixed $dir The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArchiveMessagesQuery The current query, for fluid interface
     */
    public function filterByDir($dir = null, $comparison = null)
    {
        if (is_array($dir)) {
            $useMinMax = false;
            if (isset($dir['min'])) {
                $this->addUsingAlias(ArchiveMessagesPeer::DIR, $dir['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($dir['max'])) {
                $this->addUsingAlias(ArchiveMessagesPeer::DIR, $dir['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(ArchiveMessagesPeer::DIR, $dir, $comparison);
    }

    /**
     * Filter the query on the body column
     *
     * Example usage:
     * <code>
     * $query->filterByBody('fooValue');   // WHERE body = 'fooValue'
     * $query->filterByBody('%fooValue%'); // WHERE body LIKE '%fooValue%'
     * </code>
     *
     * @param     string $body The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArchiveMessagesQuery The current query, for fluid interface
     */
    public function filterByBody($body = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($body)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $body)) {
                $body = str_replace('*', '%', $body);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(ArchiveMessagesPeer::BODY, $body, $comparison);
    }

    /**
     * Filter the query on the name column
     *
     * Example usage:
     * <code>
     * $query->filterByName('fooValue');   // WHERE name = 'fooValue'
     * $query->filterByName('%fooValue%'); // WHERE name LIKE '%fooValue%'
     * </code>
     *
     * @param     string $name The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return ArchiveMessagesQuery The current query, for fluid interface
     */
    public function filterByName($name = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($name)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $name)) {
                $name = str_replace('*', '%', $name);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(ArchiveMessagesPeer::NAME, $name, $comparison);
    }

    /**
     * Exclude object from result
     *
     * @param   ArchiveMessages $archiveMessages Object to remove from the list of results
     *
     * @return ArchiveMessagesQuery The current query, for fluid interface
     */
    public function prune($archiveMessages = null)
    {
        if ($archiveMessages) {
            $this->addUsingAlias(ArchiveMessagesPeer::ID, $archiveMessages->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
