<?php


/**
 * Skeleton subclass for representing a row from the 'archive_messages' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep 24 22:08:41 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ArchiveMessages extends BaseArchiveMessages {

   public function getCollId(){
        $user = ArchiveCollectionsPeer::retrieveByPk($this->coll_id); 
        return sprintf("%s", $user->getUs());
    }
} // ArchiveMessages
