<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/10/01 18:04:48

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=ejabberd;host=127.0.0.1',
  'username' => 'root',
  'password' => '310389rimaS!',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
