<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/10/01 18:04:47
sfConfig::add(array(
  'app_sf_guard_plugin_success_signout_url' => '@homepage',
  'app_sf_guard_plugin_remember_key_expiration_age' => 86400,
  'app_sf_guard_plugin_routes_register' => false,
  'app_sf_guard_plugin_sf_upload_dira' => 'uploads',
));
