<?php
// auto-generated by sfViewConfigHandler
// date: 2014/10/01 18:04:48
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('ipe/layout.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('../sfPropelPlugin/css/default.css', '', array ());
  $response->addStylesheet('../sfPropelPlugin/css/global.css', '', array ());
  $response->addStylesheet('ui_lightness/jquery_ui_1.8.21.custom.css', '', array ());
  $response->addJavascript('library/jquery/jquery.js', '', array ());
  $response->addJavascript('library/tiny_mce/tiny_mce.js', '', array ());
  $response->addJavascript('library/jquery/jquery_1.7.2.min.js', '', array ());
  $response->addJavascript('library/jquery/jquery_ui_1.8.21.custom.min.js', '', array ());


